// Generated by CoffeeScript 1.4.0
var client, hash, redis, url, urlalias;

url = require('url');

redis = require('redis');

client = redis.createClient();

hash = "defaultdomain";

urlalias = function(req, res, next) {
  var url_parts;
  url_parts = url.parse(req.url);
  console.log(url_parts);
  return client.hget(hash, url_parts.pathname, function(err, reply) {
    if (reply) {
      req.urlRewritten = req.url;
      req.url = reply + url_parts.search;
    }
    return next();
  });
};

urlalias.configure = function(domain) {
  return hash = domain;
};

urlalias.isExist = function(url, cb) {
  return client.hexists(hash, url, function(err, ret) {
    return cb(ret);
  });
};

urlalias.add = function(from, to, cb) {
  return client.hset(hash, from, to, function(err, res) {
    if (cb != null) {
      return cb(err);
    }
  });
};

urlalias.remove = function(url, cb) {
  return client.hdel(hash, url, function(err) {
    if (cb != null) {
      return cb(err);
    }
  });
};

module.exports = urlalias;
